### ISSUE TITLE
2019.11.04 (월) 오후 미팅 로그

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#1]
# 2019.11.04 오전 MEETING

## MEETING 목적 🚩

- [x] 브레인스토밍 2개씩
- [x]  React.js 공부하기
- [ ]  Issue / Project 관리 컨벤션
- [ ]  Label 정하기

#### 김도현
- 빅데이터활용 + 의류 구매  -> 선호도 + 추천 서비스
#### 김재원
- 댓글만 되는 플랫폼(익스텐션화)

#### 조애리
- 항공권 로그를 활용한 여행 추천 서비스(핵데이 주제)
- 교통과 관련된 데이터 활용

#### 이미림
- PDF + 채팅기능
     - 마이크 녹음 기능
    - 동영상 녹화 기능
    - 발표 종료 후 접속자에게 자료 이메일 기능 등

### 개발환경 세팅하기
- set-react-env 브랜치에서 확인 가능

- 규모는 작게 가져가자
- 기술은 깊게 공부하자

- [기획1] 을 가져가되 중심 기능에만 초점 맞추기
- 대용량 트래픽 분산 처리(김도현) 등 서버 기술 완성도 높이기

- 컴팩트 기능 완성 후 기능 추가하기 - 버전 관리
- 추가기능 ex) 익명/로그인 분리

### React 공식문서 읽어오기 ( 복습 )
* [공식문서 링크](https://ko.reactjs.org/docs/thinking-in-react.html)
* **주요 개념** 모두 읽어오기

 @loadOne @always-awake @aereeeee

**Comment by happydhKim** [comment]
확인완료!🙂

**Comment by aereeeee** [comment]
확인했습니다

**Comment by devjaewon** [comment]
확인했습니다.

**Comment by always-awake** [comment]
확인했습니다 👌
