### ISSUE TITLE
 [BUG] 전체화면 종료 후 버튼에 대한 클릭 이벤트가 동작하지 않음

### ISSUE THREAD

**Issue by hzoou** [connect-foundation/2019-02#108]
# 버그 이슈 제목
- 전체화면 종료 후 버튼에 대한 클릭 이벤트가 동작하지 않음

## 이슈 ❗️
- 전체화면 실행 종료 후 스피커 동기화 버튼이 일시적으로 클릭되지않는 버그가 있습니다.

**Comment by happydhKim** [comment]
감사합니다 혜주님!! 빠른 시일 내에 확인해 보겠습니다!

드로피 일동🐤

**Comment by always-awake** [comment]
hzoou님~ 해당 버그 해결되었습니다!
감사합니다 👍
