### ISSUE TITLE
스프린트 회의 로그 (1차) 🏃‍♀️🏃‍♂️

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#11]
# 스프린트 회의 로그 (1차) 🏃‍♀️🏃‍♂️

## 스프린트 목표 🏈

- 유저가 소셜 계정으로 로그인 할 수 있다.
- 유저가 로그아웃 할 수 있다.

## 스프린트 단위 🗓
- 3일 (2019.11.12(화) ~ 2019.11.15(금))

## 스크럼 마스터 👨‍🔧
- 조애리 @aereeeee 

## 회의 내용 💬

- 4명이 페어 프로그래밍을 진행하며 통일된 개발환경 및 개발패턴을 이해한다.
- GraphQL에 대해 학습이 필요한 주차로 일정을 여유롭게 산정한다.
- 남는 시간에 CI/CD 환경을 완료한다.

### `#1` 사용자는 SNS 계정으로 dropy에 로그인 한다.

- Issue: #9
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 2
    - 전체적인 개발환경 셋팅을 먼저 해야한다.
    - GraphQL에 대한 학습 및 구조/패턴을 정의 해야한다.
    - `passport.js` 를 이용해 빠르게 로그인 환경을 생성한다.  
(로그인 기능은 우리 프로젝트의 중점적인 기능이 아니라고 판단함)
    - 테스트 코드를 작성한다.

### `#2` 로그인 사용자는 로그아웃한다.

- Issue: #10
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 0.5
    - 로그아웃 클라이언트/서버를 구현한다.
    - 테스트 코드를 작성한다.

**Comment by happydhKim** [comment]
확인했습니다! 🤠

**Comment by aereeeee** [comment]
확인했습니다

**Comment by always-awake** [comment]
확인했습니다 👌
