### ISSUE TITLE
[BUG] URL 접근 버그

### ISSUE THREAD

**Issue by demetoir** [connect-foundation/2019-02#110]
# URL 경로에 따른 페이지 랜더링 문제

## 이슈 ❗️

* http://dropy.org/mypage/fdfdfsdf

위 URL로 접근하면 상단 네비바만 나옴

* http://dropy.org/channels/sfsdfs
위 URL로 나오면 로딩 화면만 보여짐

## 기대했던 결과 🥰

특별한 404 화면

## 현재 결과 🤭
상단 네비바만 나오고 나머지 항목이 보이지 않거나 로딩 화면만 보여짐

**Comment by happydhKim** [comment]
유준님 감사합니다  404가 아직 처리가 안되어있네요!! 빠른 시일 내에 수정하도록 하겠습니다!😍

**Comment by always-awake** [comment]
저희 서비스에 너무너무 필요했던 버그 이슈입니다~
감사합니다! 빠르게 수정하겠습니다 🙆‍♀️

**Comment by always-awake** [comment]
demetoir님 버그 이슈 해결되었습니다! 
감사합니다 🐣
