### ISSUE TITLE
[BUG] 화면에 보여지는 글씨가 맞지 않습니다.

### ISSUE THREAD

**Issue by malygos-sg** [connect-foundation/2019-02#111]
![image](https://user-images.githubusercontent.com/37038262/70301234-2b7e7180-183d-11ea-8b40-9e5bec893359.png)

해당 문구가 이탈하여 보여지는 것 같습니다.

**Comment by happydhKim** [comment]
승표님 감사합니다.  빠른 시일 내 수정하도록 하겠습니다.🤠

**Comment by always-awake** [comment]
버그 이슈 생성 감사합니다.
빠르게 수정하겠습니다 🙆‍♀️

**Comment by happydhKim** [comment]
수정했습니다.🤭
다음 배포 때 적용됩니다.
