### ISSUE TITLE
[BUG] 동영상 파일을 넣으니까 계속 로딩됨

### ISSUE THREAD

**Issue by OriginJang** [connect-foundation/2019-02#112]
# 버그 이슈 제목

- 육하원칙에 따른 자세한 설명일수록 좋다

## 이슈 ❗️

- 동영상 파일을 넣으니까 계속 로딩만됨

## 기대했던 결과 🥰

- pdf 파일을 넣어달라고 하면 좋을듯요

<br>

## 현재 결과 🤭

- 뱅글뱅글

<br>

## 관련된 이슈 📎

> 관련 이슈 없음

<br>

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by happydhKim** [comment]
감사합니다 기원님 예외처리가 아직 되어있지 않습니다. 빠른 시일 내 추가 하겠습니다. 🌝

**Comment by always-awake** [comment]
버그 이슈 생성해주셔서 감사합니다! 
빠르게 수정하겠습니다 🙆‍♀️

**Comment by always-awake** [comment]
이슈 해결되었습니다! 🐣
> 관련 [PR](https://github.com/connect-foundation/2019-02/pull/116)
