### ISSUE TITLE
[BUG] 채팅 스크롤이 가로로 생깁니다.

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#113]
# 채팅 스크롤이 가로로 생깁니다 

- 육하원칙에 따른 자세한 설명일수록 좋다

## 이슈 ❗️
- 글자를 연속적으로 길게 입력하니까 스크롤이 가로로 생깁니다~

## 기대했던 결과 🥰

- 세로로 생기는게 더 자연스럽게 느껴질 것 같습니다!

## 현재 결과 🤭
<img width="361" alt="스크린샷 2019-12-06 오후 4 51 25" src="https://user-images.githubusercontent.com/40539104/70305851-bb75e880-1848-11ea-9397-dc6c166fba29.png">

**Comment by devjaewon** [comment]
작업 완료되었습니다.
