### ISSUE TITLE
날아가는 이모지가 스피커를 방해하지 않는 정도에 대한 논의

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#118]
# [Epic#38] 이모지를 채널에 날릴 수 있다!🤭(#87)

- 채널 내에 감정표현을 하기 위해 이모지를 날릴 수 있습니다.

<br>

## 이슈 ❗️
<img width="1440" alt="스크린샷 2019-12-08 오후 3 36 13" src="https://user-images.githubusercontent.com/20928548/70385435-a5932f80-19d0-11ea-816f-405644641fd9.png">

- 현재 구현 된 이모지 날리기는 중앙에서 부터 시작해 최상단으로 휘잉휘잉 하면서 날아갑니다.
- 하지만 이게 스피커와 리스너를 산만하게 할 수 있다는 팀원들의 의견 때문에 어떤식으로 개선해야 할 지 고민해야 합니다.

<br>

## 나의 의견 😎

- 개인적으로 화면에 보이는 것도 괜찮다고 생각했습니다. 하지만 팀원들의 의견을 들어보니 다른 앱들을 참고해서 최대한 스피커를 방해 하지 않는 방식도 찾는게 좋다고 생각합니다.

## 김재원 😎

- 전체화면에서도 보이게 하자.
- 위치를 사이드 쪽으로 정해 화면을 온전히 보이게 하자.

## 이미림 😎

- 디폴드 값으로 이모지를 사용하지 못하게 하는게 좋아보이며, 채널 세팅에서 지정할 수 있도록 하는게 좋다.
- 위치를 사이드 쪽으로 정해 화면을 온전히 보이게 하자.

## 조애리 😎

- 일정 위치에 도달하면 점차적으로 사라지게 하자.
- 위치를 사이드 쪽으로 정해 화면을 온전히 보이게 하자.

<br>

## 관련된 이슈 📎

- # [Epic#38] 이모지를 채널에 날릴 수 있다!🤭(#87)

<br>

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by happydhKim** [comment]
첫 회의에서는 이모지 버튼 위치 변경 및 화면을 피해 사이드에서 나오는 것으로 결정을 했습니다.
또한 전체 화면일 경우에도 우측 사이드 쪽에서 나오는 것으로 했습니다.
애니메이션 같은 경우 중간 정도에서 서서히 화면에서 사라지는 것으로 결정했습니다.

추가적인 제안이 있으신 분은 댓글로 말씀 부탁드립니다.!🥺

**Comment by always-awake** [comment]
회의 내용 확인했습니다 👌
