### ISSUE TITLE
스프린트 회의 로그 (5차) 🏃‍♀️🏃‍♂️

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#134]
# 스프린트 회의 로그 (5차) 🏃‍♀️🏃‍♂️

## 스프린트 목표 🏈
- 버전1의 디테일 보완
- 스피커의 권한 기능 추가
- 필기도구 기능 완성
- 이모지 이펙트 기능 완성

## 스프린트 단위 🗓
- 4일 (2019.12.9(월) ~ 2019.12.12(목))

## 스크럼 마스터 👨‍🔧
- 조애리 @aereeeee

## 회의 내용 💬

- 버전 1의 디테일을 보완하자.
- 기획을 확실하게 마무리하여 버전 1을 완성하자.

### 사용자는 채팅에서 질문을 sorting할 수 있음

- Issue: #129
- Assignee: 조애리 @aereeeee
- Manday: 2
    - [ ] 해쉬태그+페이지번호 가 포함된 채팅을 질문으로 판별한다.
    - [ ] 질문보기 버튼을 눌러 해당 채팅을 소팅할 수 있다.

### 사용자는 해쉬태그(#)로 질문 채팅을 생성할 수 있음

- Issue: #130
- Assignee: 조애리 @aereeeee
- Manday: 2
    - [ ] 해쉬태그+페이지번호는 bold font로 표시된다.
    - [ ] 해당 채팅을 클릭하면 슬라이드 페이지가 이동된다.
    - [ ] 해당 채팅 말풍선은 yellow border를 가진다. 

### [Epic#21] 스피커는 채널 설정에서 익명 채팅을 활성화 할수 있음

- Issue: #131
- Assignee: 조애리 @aereeeee
- Manday: 2
    - [ ] 스피커가 채널 설정버튼을 누르면 모달창이 뜬다.
    - [ ] 모달창에서 토글 버튼으로 익명채팅을 활성화할 있다.
    - [ ] 디폴트로 익명채팅이 활성화되어있다.
    - [ ] 익명채팅을 비활성화하면 익명 사용자는 채팅이 불가하다.
    - [ ] 익명사용자가 채팅을 시도하면 placeholder 등에 로그인해주세요 라는 가이드가 표시된다.

### 슬라이드를 좌우 화살표키로 이동할 수 있음

- Issue: #133
- Assignee: 조애리 @aereeeee
- Manday: 2
    - [ ] 좌우 화살표키를 누르면 슬라이드를 이동할 수 있다.
    - [ ] 전체화면에서 좌우 화살표 키를 누르면 슬라이드를 이동할 수 있다.

### [ BUG ] 채널 페이지의 슬라이드 컴포넌트 렌더링 최적화

- Issue: #132
- Assignee: 조애리 @aereeeee
- Manday: 2
    - [ ] 현재 4번 렌더링되는 슬라이드 컴포넌트의 문제점을 파악한다.
    - [ ] 렌더링을 최소화한다.

### [BUG] 로그아웃 버튼 눌렀을 때 모달이 닫히기 전에 먼저 UI가 변한다

- Issue: #124
- Assignee: 김재원 @load0ne
- Manday: 1

### [Epic#2, Epic#23] 채널 만료기간을 수정할 수 있다

- Issue: #125
- Assignee: 김재원 @load0ne
- Manday: 1
    - 채널 설정 UI 모달이 필요하다.
    - 채널 설정 UI에서 만료기간을 설정할 수 있다.

### [Epic#5, Epic#6] 프로필 정보와 이미지를 수정 가능하다

- Issue: #126
- Assignee: 김재원 @load0ne
- Manday: 1
    - [ ] 마이페이지에서 프로필 정보를 수정할 수 있다.
    - [ ] 마이페이지에서 프로필 이미지를 수정할 수 있다.

### [Epic#20] 채널 제목을 수정할 수 있다

- Issue: #127
- Assignee: 김재원 @load0ne
- Manday: 0.5
    - [ ] 채널 제목을 수정할 수 있다.

### [Epic#26] 채널 상태태그를 수정할 수 있다

- Issue: #128
- Assignee: 김재원 @load0ne
- Manday: 0.5
    - [ ] 체널 상태태그를 수정할 수 있다.

### [Epic#22] 채널세팅에서 채널 내 수용인원을 설정할 수 있다

- Issue: #121
- Assignee: 김도현 @happydhKim
- Manday: 1.5
    - [ ] 참여인원이 몇명인지 확인할 수 있다. 이슈 완성하기.
    - [ ] 채널세팅에서 사용할 UI만들기.
    - [ ] 참여인원이 몇명인지 확인 해, 넘으면 입장 불가 하도록 설정.
    - [ ] 입장이 불가 할 때 적절한 에러 메시지 및 팝업 구현.

### 마이페이지 디자인 수정

- Issue: #122
- Assignee: 김도현 @happydhKim
- Manday: 1
    - [ ] 마이페이지의 디자인을 전반적으로 수정한다.
    - [ ] 마이페이지 히스토리 카드를 수정한다.
    - [ ] 마이페이지 유저정보 디자인을 수정한다.

### 공유 버튼 클릭시 알람을 띄워줘야 한다

- Issue: #123
- Assignee: 김도현 @happydhKim
- Manday: 0.5
    - [ ] 알람을 어떤식으로 표현할지 정한다.
    - [ ] 알람을 디자인한다.
    - [ ] 알람이 정상적으로 작동한다.

### 채널 코드 입력 후, 엔터로 채널에 입장할 수 있다

- Issue: #119
- Assignee: 이미림 @always-awake
- Manday: 0.5
    - [x] 채널 코드를 입력하고, 엔터로 채널에 입장할 수 있다.

### 로딩/에러 모달창에 돌아가기 버튼을 클릭할 수 있다

- Issue: #120
- Assignee: 이미림 @always-awake
- Manday: 0.5
    - [x] 로딩/에러 모달창에 돌아가기 버튼을 클릭할 수 있다.

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by happydhKim** [comment]
확인했습니다!🌝

**Comment by aereeeee** [comment]
확인했습니다
