### ISSUE TITLE
반응형 캔버스에서 resize 이전의 캔버스 content를 유지하는 방식 고민하기 

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#145]
# 반응형 캔버스에서 resize 이전의 캔버스 content를 유지하는 방식 고민하기
## 이슈 ❗️

- 채널 화면에서 canvas의 크기가 변경될 때, 크기 변경 이전의 canvas의 content를 유지해야 하는데, 이를 해결할 방식에 대해 논의가 필요하다.

## 나의 의견 😎
- `canvas.toDataUrl()` 또는 `canvas.toBlob()` 등의 canvas api를 이용하여, 캔버스가 resize되기 이전에 해당 canvas content를 이미지로 저장하고, 캔버스가 resize되고 난 후, 이전 이미지를 캔버스 위에 `drawImg()` api를 이용하여 그려주는 방식을 생각해보았다.
- 하지만... 위와 같은 방식은 이미지를 캔버스의 크기에 맞게 늘려주고, 줄여주기 때문에 어느정도의 손실이 발생한다...😭

## 관련된 이슈 📎

- [Epic#24, Epic#26] (스피커) 필기 도구를 이용해 슬라이드에 원하는 필기를 기입할 수 있다. (#86)
- [Epic#24, Epic#26] Canvas가 resize될 때, 이전의 Canvas content를 유지할 수 있어야 한다. (#144)

## 레퍼런스 📚
> 레퍼런스 없음

**Comment by always-awake** [comment]
자유롭게 의견 제시해주세요 🤓

**Comment by aereeeee** [comment]
### 좌표 시스템 제안
사용자가 캔버스에 필기를 할 때, x,y좌표값을 해당 캔버스 크기에 대한 비율값으로 배열 등의 구조에 저장합니다.
이를 페이지 별로 디비에 저장하여 다른 클라이언트에서도 자신의 해상도에 맞는 그림을 그립니다.

*이때, 사용자가 마우스 다운 - 마우스 업 할때까지의 흐름을 한 획으로 보고 상태값으로 저장하는 것이 필요합니다. 왜냐하면 작은 해상도에서 큰 해상도로 좌표값이 공유될 때, 그려지는 면적에 빈 공간이 생길 수 있기 때문입니다. 이에 대한 대처로 한 획으로 판단 될 경우 빈 면적을 이어주는 작업이 필요할 것입니다.

### 버퍼 캔버스 사용
재원님이 공유한 offscreencanvas를 사용하여 큰 해상도의 버퍼캔버스를 생성하는 방법입니다.
아무래도 높은 화질의 이미지를 사용하여 재렌더링하면 이미지 손실을 줄일 수 있을 것 같습니다.
하지만 이 경우에 다른 클라이언트와 동기화 작업에 이미지 스트리밍이 필요하므로 러닝커브가 약간은 있지 않을까 생각합니다.

### 현재 구현된 이미지 방식 사용할 경우
현재 확인한 결과로는 이미지가 spread되면서 blur처리가 되는 문제가 있는데 이를 해결할수 있는 캔버스 API가 있는지 찾아보았습니다. 정확한 메소드는 없고 대부분 이미지 필터 메소드를 구현하여 사용하는것 같습니다.

getImageData의 결과물은 data key안에 Uint8ClampedArray로 이미지 정보가 들어있습니다. 여기서 한 Pixel의 정보는 4개의 단위로 쪼개집니다. 예를들면 Uint8ClampedArray[0] ~ Uint8ClampedArray[3] 까지가 좌상단의 첫번째 픽셀에 대한 정보입니다. 순서대로 RGBA값, 즉 빛의 3원색인 적,녹,청의 대한 값과 alpha(밝기)에 대한 정보라로 각각의 값들은 0부터 255까지의 int값을 가질 수 있습니다. [참고]( https://dev-momo.tistory.com/entry/Javascript-Image-Filter-만들기)

이를 이용하여 픽셀에 색상이 적용된 부분을 사용한 펜툴의 색상값으로 대체하여 블러문제를 해결할수 있을 것 같습니다. 

그러나 마찬가지로 동기화에 이미지 스트리밍이 필요하다는 문제가 있겠네요!

### 프로세싱 이용하기
프로세싱을 기반으로 한 자바스크립트 라이브러리인 p5.js는 HTML 캔버스 기반으로 동작합니다. 이를 이용하면 이미지 프로세싱에 있어 기존 캔버스 보다 다양한 API를 지원받을 수 있습니다. 그중에서 vector로 캔버스 이미지를 렌더링하는 API가 있으므로 화질에 대한 걱정을 덜 수 있을 것 같습니다.

**Comment by always-awake** [comment]
애리님 답변 감사합니다! 🙆‍♀️
**현재 구현된 이미지 방식 사용할 경우** 방식에서 말씀해주셨던 필더 메소드 활용 방법은 처음 알게 됬는데 꽤 좋은 아이디어 인것 같아요! 그리고... **프로세싱 이용하기** 방식은.. 다른 두 방식으로 실험한 뒤, 한번 시도해보겠습니다 (러닝커브가 걱정되네요 😭)

저는 현재 **좌표 시스템**을 이용해 구현해보고 있습니다.
여러 방식 중, 좌표 시스템을 선택한 이유는
1. 유저가 기록한 정보를 가장 정확하게 유지할 수 있는 방식이라 생각했습니다. 
    - 저장하고, 그리는 데 큰 부하가 걸리지 않는지에 대한 고민 역시 하고 있지만, 이미지를 계속해서 스트리밍 해주는 부하보다는 덜하다고 생각합니다.
2. 이후에, 필기 동기화 기능을 추가하였을 때, 그리기 이벤트가 발생할 때마다 해당 좌표를 (가로/세로 길이를 고려한 비율 좌표) publish하도록 하여 동기화를 구현하려고 생각중입니다. 이 역시 좌표 시스템으로 구현할 생각이기 때문에 리사이즈 될 때, 이전의 canvas content를 유지/관리하는데 좌표 시스템으로 통일성있게 관리되는 것이 좋다고 생각합니다.

이 좌표 시스템 실험이..실패로 돌아간다면, **현재 구현된 이미지 방식 사용할 경우**에서 제안해주신 필더 방식을 공부해서 적용해볼 듯 합니다~ 그때 많은 도움 부탁드립니당 ㅎㅎㅎ

제안 감사합니다 많은 도움이 됬습니당 💪

**Comment by devjaewon** [comment]
저는 개인적으로 비트맵 시스템을 통해 관리하는 것이 성능 이슈를 줄이고 완성도를 높이는 방법이지 않을까 생각합니다.

현재 저희가 캔버스상에서 필기하는 것을 관리하기 위한방식으로는 크게 두가지로 나눌 수 있을 것 같습니다.

1. 비트맵 관리
- 필연적으로 리사이징시 어느정도 이미지 정보가 손실될 수 밖에 없는 자료구조라 생각합니다.
- 하지만 다음과 같은 이유로  추천합니다.
    - 이미지 상태를 배열로 관리함으로써 사용자 필기에 대한 데이터양이 한정되어있기 때문에, 메모리 최적화를 위한 비용이 적습니다.
    - 마찬가지로 배열의 길이가 한정되어있기에 탐색비용을 최적화하기도 좋습니다. (단순한 이진 탐색 알고리즘만 도입해도 성능이 올라갈듯 합니다)
    - 위에서 애리님이 공유해주신 직접 메모리 관리가 가능한 배열을 자바스크립트에서 제공해주는데 이를 이용하면 좋을듯 합니다. 지금 당장 적용하긴 시간이 부족하니, 라이브러리를 쓰는것도 좋은 방법이라고 생각합니다.

2. 벡터로 관리
- 이는 이미지 손실을 막을 수 있고, 아핀변환을 통해 리사이즈에 대응하기 쉽다는 장점이 있습니다.
- 하지만 벡터는 사용자가 사용하기에 따라 무한정 늘어날 수도 있고, 지우개 기능을 구현할때 동일한 이유로 엄청난 탐색비용이 들것으로 생각됩니다.
    - 따라서 일정량 이상 벡터가 쌓이면 최적화를 진행하여, 중첩되는 벡터들을 합치는 작업이 필요할듯한데, 이건 너무 난이도가 높지 않을까... 생각합니다.

또한 추가로 이미지 연산은 Web Worker 를 활용해서 다른 쓰레드에서 진행하는게 좋지 않을까 합니다.
