### ISSUE TITLE
로그인 관련 창 문구 개선이 필요합니다.!

### ISSUE THREAD

**Issue by SeonJun-Hwang** [connect-foundation/2019-02#157]
# 이슈 제목

- 이슈에 대한 설명(육하원칙에 따른 자세한 설명일수록 좋다)
로그인 페이지에서 구글 빼고는 로그인이 됩니다 ㅠ
문구 수정 부탁드립니다.

<br>

## 이슈 ❗️

- 어떤 문제인지 서술
- 커밋 해쉬값

![image](https://user-images.githubusercontent.com/38457114/70772855-28453180-1db9-11ea-81fe-14acd30cc6d3.png)
![image](https://user-images.githubusercontent.com/38457114/70772873-31ce9980-1db9-11ea-8ceb-189a5d4463bd.png)

<br>

## 나의 의견 😎

- 본인이 어떤 의견을 가지고 있는지 제시

<br>

## 관련된 이슈 📎

> 관련 이슈 없음

- issue title (#issue number)

<br>

## 레퍼런스 📚

> 레퍼런스 없음

- [title](link)

---

**Comment by devjaewon** [comment]
네이버 로그인 기능추가 이슈에서 해결하도록 하겠습니다.
현 이슈는 닫겠습니다.
