### ISSUE TITLE
2019.11.15 (금) 오후 미팅 로그

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#17]
# 2019.11.15 오후 MEETING

## MEETING 목적 🚩
- [x] 컴포넌트 스타일링에 대한 코드 컨벤션 확립
- [x] 리액트 컴포넌트 코드와 스타일 컴포넌트 코드 분리에 대한 논의

### `Material-UI` 와 `Styled-Components` 를 같이 사용하는 것
- 김도현
    - 두개를 같이 쓰면 Material-UI 를 커스터마이즈 해야하기 때문에 비용이 더 들 수 있다. 하지만 Material-UI를 사용하지 않는다면, CSS를 다루는 실력이 매우 향상될 수 있기 때문에 둘 다 좋은 방법이라 생각한다.
- 김재원
    - Material-UI 를 씀으로써 접근성을 자연스럽게 보완할 수 있는 장점이 있지만, 기존의 스타일을 수정해야하기 때문에, 바로 만드는 것보다 비용이 조금 더 들 것 같다는 생각이 든다. 장단점이 있기에 둘다 좋은 방법이라고 생각한다.
- 이미림
    - 일반 버튼, 토글 버튼, 모달창 등의 컴포넌트는 Material-UI를 사용하되, Wrapper 컴포넌트 (헤더, 채팅창 등)은 Styled-Component로 직접 구현하는 것이 좋다고 생각한다.
    - 컴포넌트 이름의 폴더에 리액트 컴포넌트 파일과 해당 컴포넌트 스타일 코드가 있는 styles.jsx 파일을 만들어 리액트 코드와 스타일 코드를 분리하는 것이 좋다고 생각한다.
- 조애리
    - Material-UI 를 쓰지 않았을 때 통일된 디자인 시스템을 설계해야하는 비용이 또 들 기 때문에 프로젝트 차원에서 봤을 때 쓰는 것이 더 좋을 것이다.

### `Styled-Components` 사용에 대한 컨벤션
- 김도현
    - 실무에서 사용되는 프로젝트들을 살펴봤을 때, 스타일 컴포넌트가 분리된 경우를 많이 봤는데 로직에 대한 가독성이 확실히 좋게 느껴졌다.
- 김재원
    - 스타일 테마를 컴포넌트에서 사용시 익명함수로 항상 만들어주면 가독성 측면에서 안좋아이며 공통된 로직이 눈에 너무 많이 보인다. 테마 유틸을 따로 함수로 관리해서 이를 `import` 해서 사용하자.
- 이미림
    - 스타일 컴포넌트는 가독성을 위해 별도의 파일로 분리되어있는 것이 좋을듯 하다. 파일을 분리해두고 한번에 `S` 라는 변수명을 `import` 해서 사용하자.
- 조애리
    - 스타일 컴포넌트에 css 작성시 px 값으로 넣어주기보다는 함수로 만들어서 반응형에 유연하게 대응 가능한 시스템을 만들자.

## MEETING 결과 📌
- `Material-UI`와 `Styled-Components` 를 같이 사용한다.
- `Material-UI`의 기본테마를 우리 디자인에 맞게 바꾼 후 사용한다.
- 스타일 컴포넌트를 별도의 파일로 분리해서 관리한다.
- 스타일 컴포넌트를 `import` 할때는 `S` 라는 변수명을 활용해서 한번에 한다.
- 스타일 컴포넌트 내에서 테마를 사용할 때는 테마 유틸을 만들어서 활용한다.
- 스칼라 값은 `pxToRem` 함수로 항상 반응형에 대응할 수 있는 시스템을 만들어 둔다.

**Comment by aereeeee** [comment]
확인했습니다!

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by happydhKim** [comment]
확인했습니다🐤
