### ISSUE TITLE
스프린트 회의 로그 (5차) 🏃‍♀️🏃‍♂️

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#191]
# 스프린트 회의 로그 (6차) 🏃‍♀️🏃‍♂️

## 스프린트 목표 🏈

- 버그 Hotfix 처리

## 스프린트 단위 🗓
- 4일 (2019.12.16(월) ~ 2019.12.19(목))

## 스크럼 마스터 👨‍🔧
- 이미림 @always-awake

## 회의 내용 💬
- 기술공유
    - 김도현
        - 이모지가 날아간다🤭
        - 하나의 소켓에서 여러 그룹으로 나눠 관리하기
        - converter 모듈 분리하기
    - 김재원
        - 아폴로 캐시를 활용한 무한스크롤 시스템 구현하기 (채팅 뒤에)
    - 이미림
        - 반응형 이미지, 슬라이드 구현
        - DropyCanvas 모듈화
        - Canvas 상태 비율에 맞게 유지하기
        - docker 수동배포
    - 조애리
        - 서버 모니터링, 메시지큐
        - 해쉬라우팅 등 슬라이드 렌더링 최적화를 위해 고민한 내용
        - 깃헙 액션
        - 질문채팅 유틸
    - 기술적 회고?
    - 인프라 구조도

### Help 페이지 추가

- Issue: #181
- Assignee: 조애리 @aereeeee
- Manday: 0.5
    - [ ] 우리 소개 + 데모영상(여유 있으면)
    - [ ] Help 페이지 추가
    - [ ] 로그인/로그아웃 모달에 버튼 추가

### 불필요한 UI 제거

- Issue: #180
- Assignee: 김재원 @load0ne
- Manday: 0.5
    - [ ] 프로필 수정
    - [ ] 리스너 필기도구 버튼
    - [ ] 스피커 설정 - 수용인원/만료기간
    
### 스피커 필기 리팩토링

- Issue: #179
- Assignee: 이미림 @always-awake
- Manday: 3
    - [ ] Dropy Canvs 필기 모듈 리팩토링
    - [ ] 슬라이드 이동 시, 캔버스가 초기화된다.
    - [ ] 이전 슬라이드로 이동 시, 그렸던 내용이 다시 그려진다.

### 현재 접속 인원 수를 보여준다

- Issue: #81
- Assignee: 김도현 @happydhKim
- Manday: 1
    - [x] 현재 접속 인원 수를 실시간으로 변화한다.

### 이모지 리팩토링

- Issue: #178
- Assignee: 김도현 @happydhKim
- Manday: 2
    - [ ] 날아가는 이모지를 CSS로 변환한다.
    - [ ] 날아가는 이모지를 class에서 함수로 변경한다.
    - [ ] 렌더링 최적화.

### 채팅 렌더링 개선

- Issue: #173
- Assignee: 김재원 @load0ne
- Manday: 2
    - [ ] 채팅이 20개씩만 렌더링 되야한다. 
    - [ ] 내가 채팅을 쓸 경우 항상 맨 아래로 내려가야한다.
    - [ ] 최신순의 경우 맨 아래의 채팅을 먼저 보여준다.
    - [ ] 좋아요순의 경우 맨 위의 채팅을 먼저 보여준다.

### 슬라이드 렌더링 개선

- Issue: #132
- Assignee: 조애리 @aereeeee
- Manday: 2
    - [ ] 질문 해쉬 라우팅
    - [ ] 슬라이드 리사이즈 throttle

### 추가적으로 해결할 이슈

- 리스너도 이모지 끄게 해달라
- ..일단 후순위 스케일아웃
- 좋아여 늦게 눌러지는 것 개선
- removechild error 원인파악
- 아이콘 분리

**Comment by aereeeee** [comment]
확인햇어요

**Comment by happydhKim** [comment]
확인했습니다. 이모지 같은 경우는(Issue: #178) 리팩토링을 네트워킹 데이 이후로 미뤘습니다. 사유는 시간이 오래걸리기 때문입니다.
