### ISSUE TITLE
developt 브랜치 코드 server-api 에러 발생합니다 확인부탁드립니다.

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#192]
# developt 브랜치 코드 server-api 에러 발생

### 에러 로그
<img width="672" alt="스크린샷 2019-12-19 오후 4 38 53" src="https://user-images.githubusercontent.com/40539104/71154157-3a721480-227e-11ea-8220-aa15e3a83bd0.png">

### 에러 발생 코드 파일 path
```
/Users/leemirim/Documents/boostcamp/2019-02/server-api/src/apollo/webSocket/webSocket.js
```

### 에러 발생 코드 위치
<img width="664" alt="스크린샷 2019-12-19 오후 4 39 47" src="https://user-images.githubusercontent.com/40539104/71154140-2d552580-227e-11ea-83db-baaf65b1f869.png">

**Comment by happydhKim** [comment]
감사합니다 확인해보겠습니다!🐤

**Comment by happydhKim** [comment]
수정했습니다 이슈를 닫습니다!🌝
