### ISSUE TITLE
web 클린 코드 리팩토링

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#196]
# web 클린 코드 리팩토링

- 클린코드가 아닌부분을 찾아내 리팩토링한다.
- Airbnb Style Guide를 따른다.

## 완료 조건 ✅

- [ ] 클린코드가 아닌 부분을 찾아 클린 코드 시킨다.

## 관련 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by always-awake** [comment]
언제하나요?

**Comment by happydhKim** [comment]
죄송 안해요 이슈를 닫습니다.
