### ISSUE TITLE
커밋 컨벤션 타입에 대한 추가논의 제안

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#2]
## 이슈 ❗️

- 현재 임시로 정의한 태그들은 다음과 같습니다.
- 불필요한 태그 / 추가적인 태그에 대해 논의가 필요하다고 생각합니다.

```
BUILD
CI
CHORE
DOC
FEATURE
FIX
IMPROVE
REFACTOR
REVERT
STYLE
TEST
```

## 나의 의견 😎

- UTIL 태그 추가하는 것이 좋다고 생각합니다.
- FEATURE 는 애매하고 IMPROVE 는 아닌 경우에 CHORE 라고 하기에도 애매한 경우가 있는 것 같습니다.

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by always-awake** [comment]
전 동의합니다.
이전에는 비슷한 상황에서 IMPROVE로 했었는데 있으면 좋을거 같습니다. 다른 분들은 어떠신가요 🤔?

**Comment by always-awake** [comment]
저도 새로운 커밋 타입 하나 추가 제안하고 싶습니다! 🙋‍♀️
ENV 추가했으면 좋겠습니다.
개발환경 세팅에 관련된 커밋에 사용하면 좋을거 같은데 어떠신가용?

**Comment by happydhKim** [comment]
네 저도 좋습니다.
하지만 나중에 혼돈이 있을 경우가 있을거 같은데 여기에 대해선 어떻게 생각하시나요?
가령 `CHORE` 의 범위는 어디까지 적용되는 걸까요?🤔

따라서 저는 간략하게라도 정의도 필요하다고 생각합니다.

**Comment by devjaewon** [comment]
> 하지만 나중에 혼돈이 있을 경우가 있을거 같은데 여기에 대해선 어떻게 생각하시나요?
> 가령 `CHORE` 의 범위는 어디까지 적용되는 걸까요?🤔

추상적일 수 밖에 없는 부분이라고 생각하지만 어느정도 명시해두는 것은 좋은 것 같습니다.
예를 들면 CHORE: 태그를 붙이기 애매한 기타 잡일

**Comment by aereeeee** [comment]
pull request추가 시 붙일 MERGE 타입이 있으면 좋을것 같아요!! 제안합니다.

**Comment by always-awake** [comment]
네 동의합니다! 👌모든 분이 동의하시면, 제가 Wiki 커밋 스타일 가이드에 내용 추가해놓겠습니다!

**Comment by happydhKim** [comment]
> > 하지만 나중에 혼돈이 있을 경우가 있을거 같은데 여기에 대해선 어떻게 생각하시나요?
> > 가령 `CHORE` 의 범위는 어디까지 적용되는 걸까요?🤔
> 
> 추상적일 수 밖에 없는 부분이라고 생각하지만 어느정도 명시해두는 것은 좋은 것 같습니다.
> 예를 들면 CHORE: 태그를 붙이기 애매한 기타 잡일

훨씬 좋은거 같아요🐤

> pull request추가 시 붙일 MERGE 타입이 있으면 좋을것 같아요!! 제안합니다.

좋습니다!!!
그럼 미림님 부탁드려요!!🧙‍♀️

**Comment by devjaewon** [comment]
프로젝트 완료가 임박해서 이슈 정리하겠습니다.
