### ISSUE TITLE
스프린트 회고 로그 (1차)

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#20]
# 스프린트 회고 로그 (1차) 🏃‍♀️🏃‍♂️

## 스프린트 단위 🗓
- 3일 (2019.11.12(화) ~ 2019.11.15(금))

## 스크럼 마스터 👨‍🔧
- 조애리 @aereeeee 

## 주간 회고 내용 💬

- 김도현
    - 체계적인 방식으로 개발을 진행해 나가는 부분이 재밌었습니다. 다들 자기 개성을 잃지 않고 장점들을 잘 살려서 개발을 진행하고 있다는 느낌이 들었고 좋았으며 팀원들에게 감사하다는 생각이 듭니다.
- 김재원
    - 다수가 엄격한 체계를 갖추고 페어프로그래밍한 것은 처음이지만, 4명의 시너지가 맞아서 차근차근 잘 진행된것 같다.  
    - 배포시간을 못맞춘것이 아쉽다. 다음부터는 스프린트 완료기준을 배포로 가자. 코드프리즈 시간에 맞추어 배포하자.
- 이미림
    - 모두 함께하는 페어프로그래밍 경험이 처음인데, 재밌었고 좋은 경험이었습니다. 
    - Wrap-up 을 통해 지속적으로 회의방식이나 개발방식을 개선해나가면서 계속해서 더 좋은 협업 프로세스를 만들어갔던게 특히 좋은 경험이었던 것 같습니다.
    - 도현님 같은 경우 어떤 사소한 의견들도 들어주고 반응해주는 것이 특히 좋았습니다. 미리 시스템이나 필요한 작업을 직접해보고 팀원들에게 해당 내용을 바로바로 공유해준 점도 좋았습니다.
- 조애리
    - 4명이 함께 페어프로그래밍을 한 경험은 처음이었는데, 우리가 만든 규칙을 지키며 순조롭게 개발을 진행해본 것이 아주 좋은 경험이었습니다.
    - 로그인이라는 큰 산을 첫 주에 잘 넘긴 것 같아 아주 뿌듯합니다.

## 잘했으며 앞으로 계속할 일 🍀

- 김도현
    - 빠듯한 일정이지만 목표를 달성했다.
    - passion, energy 등이 좋았다. 
- 김재원
    - 빠듯한 일정이지만 목표를 달성했다.
    - 변수를 고려한 넉넉한 일정 산정이 좋았던 것 같다.
- 이미림
    - 협업 프로세스 및 개발 방식 등에 대해 팀원 간 서로 피드백을 주면 바로 다음날 적용, 실천하려고 한 점이 좋았다.
    - 팀원의 피드백에 공감하고 피드백에 나오게 된 상황에 대해서 정확하게 인지하였기 때문에 가능했던 것 같다.

## 더 잘했으면 좋았을 일 😥

- 김도현
    - 데일리 스크럼의 의미가 불분명해진 것 같습니다. (형식적인 스크럼이 됨)
    - 앞으로는 데일리 스크럼에서 모두가 노트북을 닫고 진행(10분) 후 다같이 기록(5)합니다. 컨디션도 간단히 공유하면 좋을 것 같습니다.
- 김재원
    - 전체적으로 컨디션 관리가 아쉬웠던 것 같습니다.
    - 그 이유를 생각해봤을 때, 해야할 일을 중심으로 진행하다보니 '이거까지만 다 개발하고 가자' 라고 생각하며 자연스럽게 매일 너무 늦은 시간에 들어갔고 잠이 줄어 들었으며 컨디션 하락으로 이어졌습니다.
    - 물론 일을 할땐, 해야할 일을 중심으로 몰입해서 진행하는게 맞다고 생각하지만, 21시쯤 되면 타협의 순간을 한번 가져야 할 것 같습니다.
- 이미림
    - 세션-> 토큰 방식으로 바꾸는 바람에 하루를 더 투자해야 했습니다.
    - 우리 개발 상황을 구체적으로 생각하지 않고 기존 방법만 생각하며 '이전에 됬었으니 되겠지'라고 안일하게 여긴것이 원인이라고 생각합니다.
    - 앞으로는 우리 개발 상황에 빗대어서 구체적으로 생각해봅시다.
- 조애리
    - 일정이 생각과 달리 틀어지는 부분이 많았습니다.
    - 스크럼마스터가 전체적인 일정관리 역할도 겸하면 좋을 것 같습니다.
    - 다른 사람들도 마스터의 말에 귀기울여 주고 잘 따르는 것이 중요할 것 같습니다.

## 다음 스프린트에 적용할 것 📈

1. 앞으로는 데일리 스크럼에서 모두가 노트북을 닫고 진행(10분) 후 다같이 기록(5분)합니다. 컨디션도 간단히 공유하면 좋을 것 같습니다.

2. 스크럼마스터가 전체적인 일정관리(컨디션 관리!!) 역할도 겸하면 좋을 것 같습니다. 다른 사람들도 마스터의 말에 귀기울여 주고 잘 따르는 것이 중요할 것 같습니다.

## 스프린트 백로그 ✍️

> 완료상태: 100%

### `#1` 사용자는 SNS 계정으로 dropy에 로그인 한다.

- Issue: #9
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 3
- Status: 완료

### `#2` 로그인 사용자는 로그아웃한다.

- Issue: #10
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 0.5
- Status: 완료

**Comment by aereeeee** [comment]
확인했습니다.

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by happydhKim** [comment]
확인했습니다!🤠
