### ISSUE TITLE
sdfsdf

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#201]
# 버그 이슈 제목

- 육하원칙에 따른 자세한 설명일수록 좋다

## 이슈 ❗️

- 어떤 문제인지 서술
- 커밋 해쉬값

```javascript
소스코드, 로그, 이미지 등
...
```

## 기대했던 결과 🥰

- `<something>`

<br>

## 현재 결과 🤭

- `<something>`

<br>

## 관련된 이슈 📎

> 관련 이슈 없음

- issue title (#issue number)

<br>

## 레퍼런스 📚

> 레퍼런스 없음

- [title](link)

<br>

## Check List

> 이슈 생성시 삭제해주세요.

- [ ] issue 제목은 유의미한가?
- [ ] issue 내용은 issue 내용만 확인하고도 모르는 사람도 파악할 수 있을 정도로 기술되었는가? (무엇을, 언제, 어디서...)
- [ ] reference가 있다면 추가했는가?
- [ ] 관련 issue가 있다면 추가했는가?
- [ ] 유의미한 Label을 추가했는가?
- [ ] Assginees를 추가했는가?
- [ ] Estimate를 추가했는가?
- [ ] 관련 Milestone이 있다면 추가했는가?
- [ ] 관련 Epics가 있다면 추가했는가?

---

**Comment by happydhKim** [comment]
?
