### ISSUE TITLE
스프린트 회의 로그 (2차) 🏃‍♀️🏃‍♂️

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#22]
# 스프린트 회의 로그 (2차) 🏃‍♀️🏃‍♂️

## 스프린트 목표 🏈
- 이미지 컨버터 모듈을 만든다.
- 프레젠테이션 채널을 만든다.
- 사용자는 채널에서 채팅할 수 있다.

## 스프린트 단위 🗓
- 4일 (2019.11.18(월) ~ 2019.11.22(금))

## 스크럼 마스터 👨‍🔧
- 이미림 @always-awake

## 회의 내용 💬

- 4명이 페어 프로그래밍을 진행하며 통일된 개발환경 및 개발패턴을 이해한다.
- GraphQL, Apollo client/server에 대해 학습이 필요한 주차로 일정을 여유롭게 산정한다.

### `#1` 업로드 한 슬라이드를 이미지 형태로 볼 수 있다.

- Issue: #23
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 1.5
    - 슬라이드(pdf,ppt) 업로드가 가능하다.
    - 업로드된 슬라이드는 서버에서 이미지로 파싱된다.
    - 슬라이드 이미지는 구조화되어 서버에 저장된다.

### `#2` 파일 업로드 시 새로운 채널이 생성된다.

- Issue: #25
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 1
    - 파일 업로드 버튼 UI를 구현한다.
    - 파일 업로드 시 채널 코드가 생성된다.(util로 구현)
    - 파일 업로드 시 새로운 url의 채널 창이 켜진다.
    - 채널 데이터가 디비에 저장된다.

### `#3` 채널에 입장하여 채팅할 수 있다.

- Issue: #24 
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 2
    - 사용자가 채널에 입장할 수 있다.
    - 사용자가 채팅을 입력할 수 있다.
    - 채팅 UI에 입력 버튼이 있다.
    - 입력한 채팅이 있는 상태에서 입력 버튼을 누르면, 채팅이 화면에 나타난다.
    - 화면에 나타난 채팅이 상태에 따라 위치가 변동 된다.

**Comment by happydhKim** [comment]
확인했습니다🌝

**Comment by always-awake** [comment]
@aereeeee @load0ne  확인 부탁드립니다! 😭

**Comment by aereeeee** [comment]
확인했습니다

**Comment by devjaewon** [comment]
확인했습니다.
