### ISSUE TITLE
2019.11.07 (목) 오후 미팅 로그

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#3]
# 2019.11.07 오후 MEETING

## MEETING 목적 🚩

- [x] 앞으로 쓰일 라벨 컨벤션을 정한다

#### 팀원들의 의견

**김도현**

라벨만 보고 어떤 이슈인지 파악이 쉽게 될 수 있도록 큰 부류로 라벨을 나눈 뒤, 한 depth를 더 분류해 세부사항을 나열하는 방식이 좋을 것 같아 보입니다. 아래는 예시입니다. 추가로 중요한 순으로 색을 진하게 하는 방법도 있습니다.
- BUG : System
- BUG : Build

- Location : App
- Location : Web server

- PR target : Master
- PR target : ...
- PR action : ...

- Meeting : ...
- Feature

**김재원**

// 동일한 색상 (연하게)
- Priority: High
- Priority: Medium
- Priority: Low

// 동일한 색상
- 아이콘 Feat
- 아이콘 Bugfix
- 아이콘 Env
- 아이콘 Test
- 아이콘 Refactor
- 아이콘 Discussion
- 아이콘 Test

// 동일한 색상
- Status: Review Now
- Status: Stop Review
- Status Not now fix

**이미림**
적절하게 depth를 일부 사용하는 것이 좋다고 생각합니다.
하위 항목/단계/정도 등을 표현할 수 있는 라벨에는 depth를 사용
<br>
// 각각 다른 색상
- bug
- feat
- env
- docs

// 동일한 색상
- important: high
- important: low

**조애리**
(이슈타입에 관한 라벨)
- Docs (다큐먼트에 대해서)
- Feat (새로운 피쳐)
- Fix
- Env
- Test
- Refactor
- Discussion

(상태에 관한 라벨)
- Status : Review Now
- Status : Stop Review
- Status : Not now fix

(그외 자유롭게 추가..)
- long
- short

### 결과
하위항목 포함하는 라벨 (같은 색상으로 한다)
- Bug 
    - system
    - build
    
- Location
    - web server
    - app server

- Priority
    - high
    - medium
    - low

- Status
    - pending
    - review now
    - review stop

- Meeting
    - 기획
    - 기술
    - 일반

하위항목을 포함하지 않는 Type 라벨
- 아이콘 Feature
- 아이콘 Bugfix
- 아이콘 Environment
- 아이콘 Refactor
- 아이콘 Discussion
- 아이콘 Test

 @loadOne @always-awake @aereeeee

**Comment by aereeeee** [comment]
확인했습니다

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by devjaewon** [comment]
확인했습니다.
