### ISSUE TITLE
스프린트 회고 로그 (2차)

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#39]
# 스프린트 회고 로그 (2차) 🏃‍♀️🏃‍♂️

## 스프린트 단위 🗓
- 4일 (2019.11.18(월) ~ 2019.11.22(목))

## 스크럼 마스터 👨‍🔧
- 이미림 @always-awake 

## 주간 회고 내용 💬

- 김도현
    - 팀원들이 모두 바빴지만 일정에 맞추어 끝낸 점이 만족스럽다.
- 김재원
    - 주말에 스프린트를 다 끝내버린 느낌이라 제대로 회고가 필요한 것 같다.
- 이미림
    - 저녁엔 개인 공부시간이 필요한데 페어프로그래밍으로 매일 야근하다보니 학습시간이 없어 아쉬웠다.
- 조애리
    - 이번 스프린트 목표를 모두 도달하여 매우 기쁘지만 기술부채가 늘어나는 것 같아 걱정이다.

## 잘했으며 앞으로 계속할 일 🍀

- 김도현
    - 많은 일정을 맞춘 것은 우리가 그만큼 결속력이 높아졌다는 것 같다.
    - 내가 아닌 팀을 위해 하는 행동들이 우리를 더욱 강하게 만드는 것 같다. (주말에 개인 시간을 할애)
- 김재원
    - 다들 요구사항을 구현하는데 급급하지 않고 시간을 쪼개 학습에 투자한 것
    - 덕분에 라이브러리의 좋은 기능들을 찾아서 더 나은 코드를 만들었고, 또한 클린한 코드가 나올 수 있었다고 생각함.
- 이미림
    - 이슈 발생 시 팀원이 합심하여 해결방법을 찾는 프로세스
    - 기술 구현 외에 대한 논의가 필요할 때, 구현에 급급하지 않고 열심히 자신의 의견을 팀원들과 공유하는 것이 정말 좋았다.  
- 조애리
    - 지난 스프린트 회의에서 도입했던 `스크럼시간에 노트북 닫기`가 잘 지켜져서 만족스러웠다.
    - 페어프로그래밍 때 시간 단위로 좀더 짧게 드라이버를 교체하여 집중도가 더 높아진것 같다.
 
## 더 잘했으면 좋았을 일 😥

- 김도현
    - 일정을 제대로 지키지 못한 것이 아쉽다.
    - 구체적으로 일정을 산정하지 않아서 계획이 틀어진것 같다.
    - 앞으로는 부스트캠프 일정과 개인 일정을 스크럼 마스터가 더욱 신경써서 관리하면 좋을 것같다.
- 김재원
    - 일정을 타이트하게 잡았기에 변수에 대응하지 못해 주말까지 동원해서 기능개발을 진행해야 했던 부분이 아쉬웠다.
    - 무조건 해결해야하는 이슈와 선택적으로 해결해야 하는 이슈를 분류해서 여유있게 일정산정을 해야할 것 같다.
    - 주말은 가능하면 개발하는 시간은 없도록 하고, 공부하는 시간을 가지는 것이 좋다고 생각한다.
- 이미림
    - 스크럼 마스터로서 역할을 잘 하지 못한것 같다.
        - 마스터 클래스 시간 파악
        - `카모아`의 방문에 대해 인지하지 못한 점
    - 일정에 주의하지 않은 것이 원인이다.
    - 다른 스크럼 마스터는 일정파악에 신경써주면 좋겟다.
- 조애리
    - manday가 지켜지지 않아 아쉽다.
    - 변수를 고려하지 않고 타이트하게 manday를 산정했기 때문인것 같다.
    - 앞으로는 스프린트 백로그를 더 구체적으로 산정했으면 좋겠다.

## 다음 스프린트에 적용할 것 📈

1. 변수를 고려하여 manday를 산정하고 일정을 잡자.
2. 스크럼마스터가 부스트캠프 일정과 팀원 개인 일정을 미리 파악하자.
 
## 스프린트 백로그 ✍️

> 완료상태: 100%

### [Epic#11] 업로드 한 슬라이드를 이미지 형태로 볼 수 있다.

- Issue: #23
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 1.5
- Status: 완료

### [Epic#12] 파일 업로드 시 새로운 채널이 생성된다.

- Issue: #25
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 1
- Status: 완료

### [Epic#15, Epic#41] 채널에 입장하여 채팅할 수 있다.

- Issue: #24
- Assignee: 페어 프로그래밍(김도현, 김재원, 이미림, 조애리)
- Manday: 2
- Status: 완료

**Comment by happydhKim** [comment]
확인 했습니다🐤

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by devjaewon** [comment]
확인했습니다.
