### ISSUE TITLE
2019.11.04 (월) 오후 미팅 로그

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#4]
# 2019.11.04 오후 MEETING

## MEETING 목적 🚩

- [x] 저녁 7시 기획 회의 잊지 않기
- [ ] 기획 구체화
    - [x] 서비스 대상 구체화
    - [ ] **핵심기능(가장중요)** 
        - [ ] 기술적으로 도전적인 기능
        - [x] 서비스 대상이 느끼는 효용(=서비스의 강점)
    - [x] 간단한 UI/UX 
        - [기초 와이어 프레임](https://github.com/always-awake/CLXII/issues/9)
- [ ] 기술적으로 심화해서 고민해 볼 포인트
- [ ] 기획에 따라서 추가적으로 공부해둬야할 부분 (ex)소켓 통신 방식)

#### 김도현
![김도현](https://user-images.githubusercontent.com/40539104/67209219-ee5b4d00-f451-11e9-819f-450ecd5005bf.jpeg)

#### 김재원
![김재원](https://user-images.githubusercontent.com/40539104/67209382-37130600-f452-11e9-896f-b51b753043f3.jpeg)

#### 이미림 
![이미림](https://user-images.githubusercontent.com/40539104/67209682-c5878780-f452-11e9-90a9-a9dff16841a4.png)

#### 조애리
![조애리](https://user-images.githubusercontent.com/40539104/67209376-34181580-f452-11e9-8d10-b832ec35f752.jpeg)

#### **발표자와 청강자 사이의 커뮤니케이션이 필요한 상황**
- 수업
- 컨퍼런스 세미나, 라이트닝 토크
- 워크숍
- 부스트 캠프 마스터 클래스 마스터 클래스

##### 2-1-1. 채팅방 생성 시
* 마스터 권한
    * 만료기간 - 만료기간이 다 된 채팅방이더라도 백업 db에 저장됨
        * 만료기간 없는 채팅방(유료)
        * 만료기간이 있는 채팅방(무료)
    * 익명/로그인 채팅방
        * 익명이 가능한 채팅방
        * 로그인한 유저만 가능한 채팅방
    * 이모지 이펙트 

#### 2-1-1. 채팅방 기능
- 채팅 좋아요 순, 최근 순 등 정렬
- 이모지 채팅화면에 날리기
- 특정 채팅글에 좋아요
- 댓글창은 토글 가능, 댓글을 클릭하면 해당 슬라이드로 이동
- 지나간 발표슬라이드는 보여지도록 UX UI
#### 기타
- 슬라이드 공유 플랫폼 (추가)
- 친구가 있는 방 타고가기

**Comment by happydhKim** [comment]
확인완료!🌝

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by devjaewon** [comment]
확인했습니다.

**Comment by aereeeee** [comment]
확인했습니다.
