### ISSUE TITLE
스프린트 회의 로그 (3차) 🏃‍♀️🏃‍♂️

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#49]
# 스프린트 회의 로그 (3차) 🏃‍♀️🏃‍♂️

## 스프린트 목표 🏈

- 버전 1.0 배포
- 중간 데모 드로피로 시연하기
- 메인페이지에서 채널새성과 채널입장이 가능하다.
- 채널 페이지에서 스피커와 리스너의 슬라이드 동기화가 이루어진다.
- 채널 페이지에서 사용자 채팅이 가능하다.
- 마이페이지에서 사용자의 히스토리를 확인 할 수 있다.

## 스프린트 단위 🗓
- 3일 (2019.11.26(화) ~ 2019.11.28(목))

## 스크럼 마스터 👨‍🔧
- 김재원 @load0ne 

## 회의 내용 💬

- 목요일까지 버전 1을 배포하기 위해 MVP를 구현한다.
- 서비스를 4개의 작은 부분으로 나누어 할당하였다.
```
- Main Page : 슬라이드 드롭다운, 채널코드 생성 및 공유 
- Channel page
    - Slide : 슬라이드 뷰어, 슬라이드 동기화
    - Chat : 채팅 좋아요, 채팅 sorting
- My page: 마이페이지 UI, 유저 히스토리 조회
```

### `#11` 메인 화면에서 슬라이드를 드롭다운 할 수 있다.

- Issue: #48
- Assignee: 이미림 @always-awake
- Manday: 1
    - [ ] 메인 화면의 Drag & Drop Page에 파일을 드롭다운 할 수 있다.
    - [ ] 파일을 드롭다운하면, 파일이 `image-converter` 서버로 전송된다. 
    - [ ] `image-converter` 서버의 응답이 있기 전까지는 유저에게 `로딩화면`을 보여준다.
    - [ ] `image-converter` 서버의 응답이 `ok`라면, 채널 화면이 보여지도록 한다.
    - [ ] `image-converter` 서버의 응답이 `ok`가 아니라면(error 발생), `에러 페이지`를 보여준다.

### `#31` 채널 코드를 입력할 수 있다.

- Issue: #50
- Assignee: 이미림 @always-awake
- Manday: 1.5
    - [ ] 채널 코드를 입력할 수 있는 `Input 컴포넌트`를 생성해야 한다.
    - [ ] 만약, 입력한 채널의 코드가 다른 채널의 코드와 동일하다면, 동일한 채널 코드를 갖는 채널 목록을 보여주는 페이지가 보여진다. (채널 목록은 스크롤 되어야 한다.)
    - [ ] 채널 목록 페이지에는 `헤더`와 채널 정보가 담겨있는 `채널 카드 컴포넌트` 리스트가 보여진다.
    - [ ] 특정 카드를 클릭하면 해당 채널 페이지가 보여진다.
    - [ ] 선택된 채널 페이지로 이동할 때, 채널 컴포넌트가 로딩되기 전까지는 `로딩화면`이 보여진다.
    
### `#13, #37` 공유 버튼을 이용해서 생성한 프레젠테이션 채널 코드를 복사하고, 공유할 수 있다.

- Issue: #51
- Assignee: 이미림 @always-awake
- Manday: 1
    - [ ] 채널 내 공유하기 버튼 컴포넌트를 구현한다.
    - [ ] 버튼을 클릭하면 채널 코드가 복사된다.

### `#18, #43` 특정 채팅글에 좋아요 가능하다.

- Issue: #40
- Assignee: 김재원 @load0ne
- Manday: 2
    - 익명의 사용자에게도 익명 사용자 토큰을 넘겨주도록 인증시스템을 수정한다.
    - 좋아요을 하기 위해서 채팅 UI를 완성한다.
    - DB에 좋아요 로그를 저장한다.
    - 좋아요를 한 채팅은 다시 좋아요 하지 못하도록 한다.
    - 좋아요 상태를 채팅 UI에 표시한다.

### `#16` 채팅을 공감순/최신순으로 정렬할 수 있다.

- Issue: #45
- Assignee: 김재원 @load0ne
- Manday: 1/2
    - 채팅을 공감순으로 정렬해서 렌더링 가능하다.
    - 채팅을 최신순으로 정렬해서 렌더링 가능하다.(default)
    - 현재 정렬상태를 UI로 강조한다.

### `#17, 39` 채팅창을 토글할 수 있다.

- Issue: #46
- Assignee: 김재원 @load0ne
- Manday: 1/2
    - 채팅창 토글버튼 UI를 클릭시 채팅뷰가 토글된다.
    - 토글될 때 적절한 애니메이션이 발생한다.(옵션)

### `#3` 로그인 된 사용자는 마이페이지로 이동 할 수 있다.

- Issue: #41
- Assignee: 김도현 @happydhKim
- Manday: 1
    - [ ] 새로운 페이지를 만들어야 한다.
    - [ ] 프로젝트의 컬러에 맞는 UI를 그려야 한다.
    - [ ] 기존의 구조에 맞게 컴포넌트를 설계해야 한다.
    - [ ] 로그인 된 사용자만 사용하며, 상태를 확인해야 한다.
    - [ ] 회원정보를 담은 스키마를 정의해야 한다.
    - [ ] 채널정보를 담은 스키마를 정의해야 한다.

    
### `#7` 스피커로써 생성한 채널 목록 확인

- Issue: #43
- Assignee: 김도현 @happydhKim
- Manday: 0.5
    - [ ] 스피커와 리스너를 구별해야 한다.
    - [ ] GraphQL을 이용해 최소한의 정보를 불러와야 한다.
    - [ ] 채널 목록을 뿌려주는 UI 컴포넌트를 생성해야 한다.
    - [ ] 서버와 연동해야 한다.
    
### `#8` 스피커 히스토리카드로 채널 입장 가능

- Issue: #44
- Assignee: 김도현 @happydhKim
- Manday: 0.5
    - [ ] 스피커와 리스너를 구별해야 한다.
    - [ ] GraphQL을 이용해 최소한의 정보를 불러와야 한다.
    - [ ] 히스토리카드 UI 컴포넌트를 생성해야 한다.
    - [ ] 서버와 연동해야한다.

### `#10` 리스너 히스토리 카드를 통해 채널로 입장 가능

- Issue: #44
- Assignee: 김도현 @happydhKim
- Manday: 0.5
    - [ ] 스피커와 리스너를 구별해야 한다.
    - [ ] GraphQL을 이용해 최소한의 정보를 불러와야 한다.
    - [ ] 히스토리카드 UI 컴포넌트를 생성해야 한다.
    - [ ] 서버와 연동해야 한다.

### `#14, #35` 슬라이드를 앞뒤로 넘길 수 있다.

- Issue: #42 
- Assignee: 조애리 @aereeeee
- Manday: 1
    - [ ] 슬라이드 뷰어 UI 구현 
    - [ ] 슬라이드 애니메이션 구현
    - [ ] 이미지 로딩 프로세스 구현

### `#32` 스피커의 화면을 동기화하여 볼 수 있다.

- Issue: #47 
- Assignee: 조애리 @aereeeee
- Manday: 2
    - [ ] 스피커의 위치를 리스너가 subscription해야한다.
    - [ ] 슬라이드 동기화 버튼 UI구현
    - [ ] 동기화 활성화 시 리스너와 스피커의 슬라이드가 동기화 된다.

**Comment by happydhKim** [comment]
확인했습니다 화이띵!!!🤠

**Comment by always-awake** [comment]
확인하고, 이슈 생성했습니다! 
이번주 스프린트도 화이팅합시다 👊

**각자의 스프린트 백로그에 `이슈 번호` 추가해주세요 🚨**

**Comment by devjaewon** [comment]
확인했습니다~~~ 화이팅!!! 💪
