### ISSUE TITLE
2019.11.05 (화) 오후 미팅 로그

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#5]
# 2019.11.05 오후 MEETING

## MEETING 목적 🚩

- [x] 기획 구체화
    - [x] 서비스 대상 구체화
    - [x] **핵심기능(가장중요)** 
        - [x] 기술적으로 도전적인 기능
        - [x] 서비스 대상이 느끼는 효용(=서비스의 강점)
    - [x] 간단한 UI/UX 
        - [기초 와이어 프레임](https://github.com/always-awake/CLXII/issues/9)
- [x] 기술적으로 심화해서 고민해 볼 포인트
- [ ] 기획에 따라서 추가적으로 공부해둬야할 부분 (ex)소켓 통신 방식)

### 플랜 B
- 이미림: 
    - 옵션을 통해 최적 예약해주는 서비스
    - 스카이스캐너처럼 영화 상영정보 스크랩핑 + 예약
    - 클라우드 펀딩 
- 김도현:
    - 헤어스타일 db화, 추천
- 조애리:
    - 내기 사이트(feat. 토토) + 음식 결제
    - 비트코인 투자
- 김재원: 
    - 드라이브
    - 댓글 익스텐션
    - 코드 테스트 시각화 서비스

---

#### 발표자 유저 스토리
발표준비자는 pdf를 가지고 있다.
우리 서비스에 접속한다.

메인화면은 방 입장 UI, 로그인/회원가입 UI, pdf드롭다운 UI를 가진다 

로그인 사용자에 한하여 pdf를 드롭하라고 안내한다.
pdf를 드롭하면 새로운 방이 생성된다.(url) 🍎(파일스트리밍)
설정탭에서 방 옵션(익명, 만료기간)을 변경할수 있다. (디폴트는 익명, 만료기간00)

발표자는 코드 혹은 링크를 공유할수 있다.
발표자는 슬라이드를 양옆으로 넘길수 있다.
발표자는 채팅창을 토글할 수 있다.

발표자는 발표자 도구로 하이라이팅, 그림그리기, 지우기 등을 할 수 있다. 🍎
사용자는 발표자의 필기를 동기화하여 확인할 수 있다. 🍎
    -> 해당 기능은 토글 할 수 있다

발표자는 발표가 끝나면 발표자료 공유하기 버튼을 누를 수 있다.

---
#### 참여자 유저 스토리

유알엘(or 룸코드)을 받은 참여자는 슬라이드 방에 입장할수 있다.
발표자의 슬라이드 화면을 동기화하여 볼 수 있다.
참여자는 이전 슬라이드를 넘겨 확인할 수 있다.
참여자는 발표자 동기화 버튼을 눌러 현재 발표중인 슬라이드로 이동할 수 있다.

채팅창을 토글할 수 있다.
채팅을 좋아요 순, 최신 순으로 정렬할 수 있다.

질문이 생기면 채팅으로 질문을 남긴다.
질문은 해당 슬라이드 (번호)를 포함하여 클릭시 해당 슬라이드로 이동한다.

각각의 말풍선(채팅 화면 내 말풍선)은 좋아요 버튼을 가진다.

발표자가 발표를 마치면 참여자는 슬라이드를 자유롭게 확인할 수 있다.
발표자가 발표를 마치고 발표자료 공유버튼을 누르면 자료를 다운로드 할수 있다.🍎

---

#### 로그인 유저 스토리
로그인 유저는 마이페이지를 확인할 수 있다.
마이페이지에는 발표히스토리, 참여히스토리를 가진다.

---
#### 준비완료 버튼 및 투표
방장이 준비완료 버튼을 누르면 나머지 참가 사람에게 준비되셨나요? yes or no alert 창이 떠서 출석 체크를 가능하다.
투표도 비슷한 방식으로 진행

#### 방장의 채팅 드래그 앤 드랍
방장이 채팅에 있는 이미지 및 다른 사람이 쓴 글을 드래그 앤 드랍하면 원하는 만큼 메인 화면에 노출 시켜 줄 수 있다.

#### 채팅의 이모티콘 및 좋아요 버튼
방장의 설명 및 채팅에서 좋은 글이 있다면 좋아요 버튼을 누를 수 있고 잠시동안 노출 시킬 수 있다.

 @loadOne @always-awake @aereeeee

**Comment by happydhKim** [comment]
확인완료!🤠

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by devjaewon** [comment]
확인했습니다.
