### ISSUE TITLE
스타일드 컴포넌트 테마 유틸 적용시 memoize 패턴 적용 제안

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#52]
# 스타일드 컴포넌트 테마 유틸 적용시 memoize 패턴 적용 제안

- 현재 테마 스타일 적용 시 currying 을 활용한 익명함수를 생성해서 넣어주고 있습니다.
- 따라서, 앱의 규모가 커질수록 동일한 기능을 하는 함수가 중복되는 현상이 더욱 커질 것으로 생각됩니다.
- 스타일 유틸에 memoize 패턴 적용을 하는 것이 미래를 위해서 좋을 것이라 생각합니다.

## 이슈 ❗️

- 16px 같은경우 폰트에서 아주 많이 사용될텐데, 매번 새로운 익명함수가 생성됩니다.
- 큰 문제가 되지 않을 수 있지만, 불필요한 중복이 발생되고 있다고 생각합니다.

<img width="641" alt="스크린샷 2019-11-26 오후 4 42 12" src="https://user-images.githubusercontent.com/47515936/69609239-611ca100-106c-11ea-98bf-29572b971d3c.png">

<img width="641" alt="스크린샷 2019-11-26 오후 4 41 31" src="https://user-images.githubusercontent.com/47515936/69609245-62e66480-106c-11ea-967f-156b3e2282f8.png">

## 나의 의견 😎

- `memoize` 패턴의 경우 일반적으로 연산이 오래걸리는 작업을 캐싱해두는 기법이지만, 지금의 상황에서 기존의 코드를 건드리지 않고 중복을 줄이는 방식으로 쓸 수 있다고 생각합니다.

```javascript
const memoize = (fn) => { /* TODO */ }
const px = memoize((val) => ({ theme }) => theme.typography.pxToRem(val));
```

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

- [위키-메모이제이션](https://ko.wikipedia.org/wiki/%EB%A9%94%EB%AA%A8%EC%9D%B4%EC%A0%9C%EC%9D%B4%EC%85%98)

**Comment by happydhKim** [comment]
저도 대책이 필요할 거 같아요. 이미 px 함수를 여러번 호출하는 현상이 점점 잦아지는거 같아요.
 제시해 주신 방식이 좋아보이네요!!🐤🐤

저는 재원님 의견에 찬성입니다.

**Comment by aereeeee** [comment]
넵 memoization이 필요할것 같네요!! useCallback과 같은 역할을 하겠네요! 저도 여건이 된다면 해당 유틸 개발에 함께하고싶네용😊

**Comment by devjaewon** [comment]
굳굳~ 적용하겠습니다!
