### ISSUE TITLE
슬라이드 이미지 요청 방식 어떤 것이 좋을까요?

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#53]
# 슬라이드 이미지 요청 방식 어떤 것이 좋을까요?

## 이슈 ❗️

- 채널 접속시 슬라이드 이미지를 가져오기 위한 초기 계획은 아래와 같습니다.
 1. 고유한 채널 아이디를 이미지 directory로 하여 오브젝트 스토리지에 저장
 2. 채널 접속 시 해당 directory에 접근하여 내부의 모든 이미지 파일 url을 요청하는 api구현

2번을 수행하기 위해서는 aws-sdk 모듈과 s3모듈이 필요합니다. 해당 모듈의 listObject메소드를 통해 특정 디렉토리의 모든 파일을 읽어올 수 있습니다.  그러나 사용자가 채널에 접속할때마다 오브젝트 스토리지의 파일을 읽는 것은 상당한 리소스 낭비라고 보여집니다. 
<br>

## 나의 의견 😎

1. api를 따로 만들지 않고 기존 channel 관련 graphQL 로직이 url 데이터를 처리하기.
```
- 채널스키마에 배열 타입의 slideUrls 필드 추가   
- converter server에서 오브젝트 스토리지에 업로드 후 응답에 slideUrls 포함
-slideUrls를 createChannel resolver를 통해 DB에 저장
- checkChannel resolver에서 slideUrls도 함께 return 하도록 수정
- 클라이언트의 채널컨텍스트가 slideUrls 배열을 하위 컴포넌트에 provide하도록 수정
```
이렇게 수정한다면 `checkChannel`이라는 resolver의 네이밍도 변경이 필요할 것 같습니다.
단순히 채널의 상태를 체크하는 쿼리에서 채널 정보를 요청하는 쿼리로 바뀌는 것이기 때문입니다.
`getChannelInfo`는 어떨까요?

2. 전체 슬라이드 페이지 수를 DB에 저장하고 클라이언트에서 해당 파일 경로를 찾기.  

현재 오브젝트 스토리지에 업로드되는 파일 경로는 아래와 같은 규칙을 가집니다.
```
https://kr.object.ncloudstorage.com/dropy/2SjwdQ3Med4gpRP11XDGvu/slides/1
```
따라서 전체 페이지수와 채널 아이디만 알고 있으면 클라이언트 단에서 모든 슬라이드 이미지에 접근이 가능합니다.
사실상 오브젝트 스토리지의 이미지에 쉽게 접근하기 위해 위와 같은 규칙으로 url을 설계한 것이므로, 이 방식을 사용하는 것도 괜찮다고 생각합니다.
  
슬라이드 이미지 요청 방식과 resolver네이밍에 더 좋은 아이디어가 있다면 제안해 주시면 감사하겠습니다~😊
<br>

## 관련된 이슈 📎

- 슬라이드를 앞뒤로 넘길 수 있다 (#42)

<br>

## 레퍼런스 📚

- [s3-listObjects](https://www.npmjs.com/package/s3#clientlistobjectsparams)

---

**Comment by always-awake** [comment]
제 의견은 애리님은 **첫번째 제안**이 좋은 것 같습니다. 제가 채널 드롭다운 후 채널 페이지로 이동하는 로직을 담당하고 있는데, 컨버트 서버에서 파일을 슬라이드로 변환 한 후에 채널페이지로 동기적으로 이동하다보니 이 지점에서도 로딩 시간이 꽤 소요된다고 느껴졌습니다. 때문에 채널로 입장하기까지 최대한 변환 시간 외의 시간 리소스를 줄여야한다고 생각합니다. 결과적으로, 컨버터 서버의 응답에 오브젝트 내 슬라이드에 대한 정보를 담아 프로바이더로 하위 컴포넌트에게 뿌려주어 클라이언트 -> 서버로의 요청 수를 줄이는 것이 좋다고 생각합니다. 
많이 고민하신게 느껴집니당 배워갑니다ㅎㅎ

**Comment by happydhKim** [comment]
저도 첫 번째가 좋지 않을까 생각합니다. 저희 서비스가 많은 사람들이 사용한다고 생각하면 서버의 요청수를 줄이는 것이 가장 중요하다고 생각합니다.🐶

**Comment by devjaewon** [comment]
저도 첫번째 제안에 동의합니다. 👍

- 슬라이드 이미지 자원 주소가 하나의 데이터로 취급되어야 한다고 생각합니다.
    - 슬라이드 넘버와, 고정적인 Object Storage URL 을 조합해서 url 로 사용하는 것은 추후 URL 형식이 바뀔 때 수정할 일이 더 많이 생기지 않을까 합니다.
- `getChannelInfo` 네임이 좋다고 생각합니다. 😊

**Comment by aereeeee** [comment]
답변 감사합니다. 1번 방식으로 적용하여 구현하였습니다! 
PR 확인해주시면 감사하겠습니다 #65 (리스너-스피커 화면 동기화 구현 완료)
