### ISSUE TITLE
2019.11.06 (수) 오후 미팅 로그

### ISSUE THREAD

**Issue by devjaewon** [connect-foundation/2019-02#6]
# 2019.11.06 오후 MEETING

## MEETING 목적 🚩

- [x] 프로그래밍 언어
- [ ] pdf, ppt 파싱 기술
- [x] 클라이언트
    - [x] 상태관리
    - [x] 뷰
    - [x] 스타일링
    - [x] ajax 통신
- [x] 서버
    - [x] 프레임워크
    - [x] 데이터베이스
    - [x] ORM
    - [x] 캐싱
- [x] 인프라
    - [x] micro service architecture
    - [x] CI/CD

### 저번 주 무엇을 고민해봤나요?

- 김도현
    - prop-types
    - Next : express + router + react
    - Redux, Redux-saga
    - React-Router

- 김재원
    - ppt serving
    - GraphQL
    - Redux-Saga

- 이미림
    - redux/redux saga vs graphQL
    - ts vs js
    - graphQL vs socket io

- 조애리
    - Github Actions
    - Jenkins
    - Docker

#### 언어

- Typescript (Fix)

#### GraphQL 왜 써야하는가

- Fetching 할때 1번의 request 로 필요한 데이터만 얻어오기 위해서(한 페이지에 여러 컴포넌트 있는 우리 서비스에 적합)
- Query 캐싱기능을 활용할 수 있다.
- 주변 고수의 강력한 추천.
- REST API: big data + GraphQL: plain data
- 단점
    - `Http caching 지원하지 않음`
    - `base64 인코딩`

#### 상태관리

- next
    - server-side-rendering
    - 검색 최적화
    - 초기로딩 빠르게
    - page 단위 플랫폼 vs 클라이언트 앱

- GraphQL (Fix)
    - apollo-client
    - apollo-server
    - websocket (ie10+) + PubSub(Redis)

#### styled-components

- styled-components (Fix)
    - 스타일 동적 관리 (반응형 쉬움)
- material-ui (Fix)
    - antd vs material-ui (경험상 material-ui 가 더 편하다고 판단)

#### ppt, pdf

- ppt/pdf/md/xls (현실적)
    - image converter server
    - image slide viewer
- ppt -> object -> ppt viewer (좋은 모듈...?)

#### test

- jest (Fix)
    - unit test (협업환경)

#### DB

- erd 중요포인트가 달라짐
    - sql - 중복성 줄이는 정규화 / nosql - 대용량 빠르게 처리
- mongoDB (Fix) - mongoose(odm - object data mapping)
- typescript 에 잘맞는 orm 찾기(orm - object relational mapping)

#### 인프라/보안

- msa(micros service architecture)
    - nginx (ssl 인증)
    - web application server (React.lazy => code split)
    - chat server
    - image converter server
    - image server
    - graphql api server

- CI / CD (Fix)
    - github actions (github 저장소 사용 연동 편리하지 않을까 생각해서...)
    - 테스트 통과 시 merge-> actions로 build, test실행 -> docker image build -> deploy
    - 컨테이너만 재가동

### 기술 목록

- 프로그래밍 언어: Typescript
- pdf, ppt 파싱 기술: imagemagick, libreoffice
- 클라이언트
    - 상태관리: apollo-client
    - 뷰: react.js
    - 스타일링: styled-components
    - ajax 통신: apollo-client
- 서버
    - 프레임워크: express
    - 데이터베이스: mongoDB
    - ORM: mongoose.js
    - 캐싱: redis.js + 캐싱전략
- 인프라
    - micro service architecture: web, api, image converter, image
    - CI/CD: docker, github actions

### 공부해야할 우선순위

1. Typescript
2. GraphQL
3. ppt, pdf 서빙 혹시 더 좋은 방법 / 관련 모듈
4. Github Action / Docker

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by happydhKim** [comment]
확인 완료!!😆

**Comment by devjaewon** [comment]
확인했습니다.

**Comment by aereeeee** [comment]
확인했습니다
