### ISSUE TITLE
회의룸에서 미팅시 제안

### ISSUE THREAD

**Issue by happydhKim** [connect-foundation/2019-02#7]
## 이슈 ❗️

- 회의룸에서 미팅시에 논리적으로 이야기하는 훈련이 필요해 보입니다.
- 추 후에 데모를 할 때, 훈련이 필요해 보입니다. ( 제가 발표를 잘 못하기도 합니다.🐤 )

## 나의 의견 😎

- 회의룸에서 미팅을 할 때, 본인의 의견을 이야기를 논리적으로 이야기 합니다.
- 이 때, 본인의 의견을 말하는 사람은 일어서서 세명을 마주하며, 화이트보드를 적극 활용했으면 좋겠습니다.
- 또한 남은 세 명의 팀원도 역시 논리적으로 반박을 하며, 논리력을 같이 향상시켰으면 좋겠습니다.

## 관련된 이슈 📎

> 관련 이슈 없음

## 레퍼런스 📚

> 레퍼런스 없음

**Comment by aereeeee** [comment]
어떤 미팅인지에 따라 다를것 같은데, 자유로운 분위기에서 활발하게 의견을 공유하는 것이 도움이 되는 미팅도 많을것같습니다. 그래서 말하는 사람이 서서 화이트보드를 쓰며 이야기하는것은 조금 제약적인 것이 아닌가 생각합니다!
논리적으로 이야기하고 논리적으로 반박하는 것은 동의합니다~~
발표준비 미팅을 따로 잡아서 해당 시간에는 도현님의 의견처럼 연습하는 것은 어떨까요?😺

**Comment by always-awake** [comment]
도현님, 애리님 의견에 동의합니다. 👌
저는 회의 유형을 구분해서, 그 회의에 맞는 준비 자세/자료와 분위기, 규칙등을 정해보는것도 좋을거 같습니다.
예를 들어,
```
- 기술/기획회의 
    - 자신의 의견에 논리적인 근거 준비한다.  
    - 회의 전에 팀원들이 읽어볼만한 자료를 공유한다.
    - 진지하고, 논리적이게 회의에 임한다.
- 브레인 스토밍
    - 배경조사 정도로 가볍게 자료조사를 하고, 편한 마음으로 회의에 참여한다.
    - 브레인 스토밍인 만큼 엉뚱한 주제가 나오더라도 그 사람을 비난/비판하지 않는다.
    - 가벼운 조크도 OK!
```
어떠신가용? 🤔

**Comment by devjaewon** [comment]
저도 회의를 할 때 자신의 의견을 확실히 논리적으로 펼칠 수 있어야한다고 생각합니다.  
- 다만 화이트보드를 사용하는 것과 서서 말하는 것은 처음 제안하는 사람만 하는 것으로 분명히 해두면 어떨까 생각합니다.
- 추가로 질문을 적극적으로 하는 연습도 겸하면 좋을 것 같습니다.

**Comment by always-awake** [comment]
앗 그리고 회의룸 규칙에 관해서 또 제안할 사항이 있습니다! 🙋‍♀️
회의실 빌리는게 그날그날 즉흥적이다라고 생각되는데, 전달 Wrap-up 시간에서 다음날 일정을 기록할 때, 회의룸을 빌릴 적절한 시간을 함께 이야기해보고, 일정에 기록하면 어떨까요?

**Comment by happydhKim** [comment]
@aereeeee @always-awake @load0ne 

🤔맞는 말씀이십니다! 애리님! 굳이 한명씩 계속 일어나서 이야기를 하다보면 너무 소비가 심할거 같아요!

미림님이 이야기 했을 때 처럼, 분류를 나눠서 그런 기회가 있었으면 좋겠습니다.

**Comment by happydhKim** [comment]
모두의 의견을 총합해서, 의견을 낸 사람이 처음으로 발표를 합니다.
다른 사람들은 모두 적극적으로 참여해 본인의 의견을 내는 것으로 마무리 합니다!👩🏻‍🍳
