### ISSUE TITLE
2019.11.08 (금) 오후 미팅 로그

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#8]
# 2019.11.08 오후 MEETING

## MEETING 목적 🚩

- [x] 프로그래밍 언어
- [x] 인프라 아키텍쳐

### 타입스크립트 vs 자바스크립트
* 새로운 언어를 선택했을 경우, 비용 발생
    * 팀원 1명을 제외한 사람들은 해당 언어가 처음
    * 개발속도 저하
    * typescript가 추구하는 코드 스타일 숙지 등에서 발생하는 시간적 비용
    * graphQL과 같은 다른 라이브러리와 타입스크립트를 함께 사용할 경우 발생하는 문제에 대한 정확한 예측/예상이 어려움

### 인프라
- web 서버 (클라이언트)
- api/chat/image 서버
- mongo db 서버
- image converter 서버
- redis 캐싱 (추후 생각하자)
(분리 된 도커 컨테이너)

### 마이크로 서비스를 DB에도 적용할 것인가?
- mongo db 서버 (mater/slave)?
- 일단은 하나로 가자

### SQL vs NoSql
- 채팅과 같은 로그 형태의 데이터, 빠른 처리가 필요한 데이터에는 NoSql이 적당

## MEETING 결과 📌
- 자바스크립트를 사용하자.
- 자바스크립트로 버전 1.0을 완성하고, 추가되는 새로운 모듈의 개발 언어를 typescript를 이용해 개발해보자.
- 인프라에 대한 논의는 호눅스 마스터님께 물어본 뒤 한번도 회의 시간을 갖자.
- NoSql로 가자!

**Comment by happydhKim** [comment]
확인했습니다!🐤

**Comment by always-awake** [comment]
확인했습니당 👌

**Comment by devjaewon** [comment]
확인했습니다.
