### ISSUE TITLE
스프린트 회의 로그 (4차) 🏃‍♀️🏃‍♂️

### ISSUE THREAD

**Issue by aereeeee** [connect-foundation/2019-02#89]
# 스프린트 회의 로그 (4차) 🏃‍♀️🏃‍♂️

## 스프린트 목표 🏈
- 캔버스 기반의 그리기 툴을 발표자에게 제공한다.
- 기존에 버그가 발생하던 부분을 수정한다.
- 슬라이드 전체화면 등 슬라이드 화면을 개선한다.
- 스트레스 테스트를 통해 슬라이드 컨버터 서버를 개선한다.

## 스프린트 단위 🗓
- 4일 (2019.12.2(월) ~ 2019.12.5(목))

## 스크럼 마스터 👨‍🔧
- 김도현 @happydhKim

## 회의 내용 💬

- 버전 1.0이 완성된 시점에서 새로운 기능을 만듬과 동시에, 내실을 다질 필요가 있다.
- 처음 사용해보는 기술스택들이 많기에 서로 협력해서 진행하자.
- 데모 때 받은 피드백들을 반영해서 개발 우선순위를 정하자.

### [컨버터 서버 성능 개선] stess test로 병목구간 찾기 

- Issue: #80 
- Assignee: 김재원 @load0ne, 조애리 @aereeeee
- Manday: 2
    - [ ] 테스트 시나리오 짜기
    - [ ] ngrinder 테스트 스크립트 짜기
    - [ ] 테스트용 mock 서버 만들기
    - [ ] 테스트 및 모니터링 진행
    - [ ] 결론(병목구간 및 개선 필요점) 도출

### [컨버터 서버 성능 개선] 성능 최적화 인프라 설계 

- Issue: #84 
- Assignee: 김재원 @load0ne, 조애리 @aereeeee
- Manday: 1.5
    - [ ] 최대 서버 인스턴스 2개 이내로 성능 개선 방안 찾기

### [컨버터 서버 성능 개선] 방어 시스템 설계 

- Issue: #83 
- Assignee: 김재원 @load0ne, 조애리 @aereeeee
- Manday: 1.5
    - [ ] 감당할 수 없는 트래픽이 몰려도 서버가 터지지 않는 방어 시스템 설계하기

### [Epic#24, Epic#26] (스피커) 필기 도구를 이용해 슬라이드에 원하는 필기를 기입할 수 있다.
- Issue: #86
- Assignee: 이미림 @always-awake
- Manday: 3
    - 채널 화면 좌측의 필기 버튼 UI 구현
    - '볼펜' 필기 도구 버튼이 활성화되면, **슬라이드 내**에서만 필기도구로 필기를 할 수 있어야 한다.
    - '지우개' 필기 도구 버튼이 활성화되면, 슬라이드 내 필기를 지울 수 있어야 한다.
    - '형광펜' 필기 도구 버튼이 활성화되면, **슬라이드 내**에서만 필기 도구로 필기를 할 수 있어야 한다. (역시 지우개로 지울 수 있다.)

### [Epic#25, Epic#33] 필기 가리기 버튼을 클릭하면, 스피커의 필기 내용이 삭제된다.
- Issue: #88
- Assignee: 이미림 @always-awake
- Manday: 1
    - 필기 가리기 버튼 UI 구현
    - 스피커는 필기 가리기 버튼을 클릭하면, 자신의 필기를 보이지 않게 할 수 있다.
    - 리스너는 필기 가리기 버튼을 클릭하면, 스피커의 필기를 보이지 않게 할 수 있다.

###  [Epic#29, Epic#36] 자료 다운로드 버튼을 활성화할 수 있다.

- Issue: #82
- Assignee: 김도현
- Manday: 0.5
    - [ ] 다운로드 버튼이 필요하다.
    - [ ] 기존 UI에 맞춰 버튼을 생성한다.
    - [ ] Object Storage에 있는 URL을 불러올 수 있다.
    - [ ] 다운로드가 정상적으로 작동한다.

###  [Epic#30] 채널에 참여인원이 몇명인지 확인할 수 있다.

- Issue: #81 
- Assignee: 김도현
- Manday: 0.5
    - [ ] 채널에 사람인원을 표시해줄 Input이 필요하다.
    - [ ] 채널에 입장한 사람들을 실시간으로 확인할 수 있다.

###  [Epic#27, Epic#34] 채널의 슬라이드를 전체화면으로 볼 수 있다.

- Issue: #85 
- Assignee: 김도현
- Manday: 1
    - [ ] 채널에 있는 슬라이드를 전체화면으로 전환시킬 수 있다.
    - [ ] 전체화면일 때, 동기화가 이루어 져야 한다. ( 리스너 )
    - [ ] 가능하다면, 전체화면에서 특정 작업을 진행할 수 있다.( 이벤트 )

###  [Epic#38] 이모지를 채널에 날릴 수 있다!🤭

- Issue: #87 
- Assignee: 김도현
- Manday: 2
    - [ ] 이모지를 선택할 수 있는 버튼이 필요하다.
    - [ ] 이모지를 선택하는 버튼을 Click or Hover하면, 사용가능 한 이모지들이 나열된다.
    - [ ] 이모지를 클릭하면, 이모지가 슬라이르 쪽으로 랜덤한 방향으로 날라간다.
    - [ ] 이모지가 날라가기 시작하면, 채널 내 모든 사람들이 날라가는 이모지를 볼 수 있다.
    - [ ] 이모지가 하나가 아닌 여래가도 정상적으로 잘 날아간다.
    - [ ] 이모지가 일정 height에 도달하면, 남지 않고 파괴된다.(🤭)

**Comment by always-awake** [comment]
확인했습니다 👌

**Comment by devjaewon** [comment]
확인했습니다. 이번주도 파이팅입니다!

**Comment by happydhKim** [comment]
확인했습니다 화이띵해요!!🤠
