### ISSUE TITLE
채널에서 채팅 글 좋아요 클릭 시, 채팅글이 여러개 중복 생성되는 이슈 발생 😭 

### ISSUE THREAD

**Issue by always-awake** [connect-foundation/2019-02#99]
# 채널에서 채팅 글 좋아요 클릭시, 채팅글이 여러개 중복 생성되는 이슈 발생
## 이슈 ❗️
- 채널 내 채팅 컴포넌트에 버그가 있는 것 같습니다.
- 현재 관련된 코드는 develop에 merge된 상태입니다.

## 기대했던 결과 🥰

- 채널에서 채팅 글 좋아요 클릭 시, 좋아요를 클릭한 한개의 채널 카드에만 좋아요가 표시되는 것

## 현재 결과 🤭
- 채널에서 채팅 글 좋아요 클릭 시, 채팅 글이 여러개 중복으로 생성되는 이슈가 발생하였습니다.
- 기존에는 발생하지 않았지만, ToolBar 컴포넌트 내에 PenTool 컴포넌트를 구현할 때, 발생한 이슈입니다.
- 중요) 최초 채널 생성 시에는 해당 버그가 발견되지 않지만, 새로 고침이나 채널 코드로 다시 방에 입장했을 때부터 위와 같은 버그가 발견됩니다. 

<img width="351" alt="스크린샷 2019-12-03 오후 1 48 51" src="https://user-images.githubusercontent.com/40539104/70021628-a98c0f80-15d4-11ea-9a41-da74743eb807.png">

## 관련된 이슈 📎
- (스피커) 필기 도구를 이용해 슬라이드에 원하는 필기를 기입할 수 있다. (#86)

## 레퍼런스 📚
> 레퍼런스 없음

**Comment by devjaewon** [comment]
해당 이슈 해결되어 이슈 닫겠습니다.
